---
- name: Create AWS Key Pair Using Ansible's Key
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    
    - name: Create AWS Key Pair Using Ansible's Key
      ec2_key:
        name: ansible_keypair
        region: "{{ aws.region }}"
        id: rhel8soe1
        force: yes
        access_key: "{{ aws.access_key }}"
        secret_key: "{{ aws.secret_key }}"
        key_material: "{{ lookup('file'), '/home/ansible/.ssh/id_rsa.pub)' }}" 
        state: present