---
- name: Get AMI Metadata
  hosts: localhost
  connection: local
  gather_facts: True
  become: False
  
  tasks:
    
    - name: Get AMI Metadata
      ec2_ami_info:
        image_ids: "{{ aws.ami_id }}"
        region: ap-southeast-2
        aws_access_key: "{{ aws.access_key }}"
        aws_secret_key: "{{ aws.secret_key }}"
      register: ami_metadata

    - name: Print AMI Metadata
      debug: 
        var: ami_metadata

    - name: Create AMI Metadata Text File
      file:
        state: touch
        path: /tmp/metadata.txt
        mode: '0644'
        owner: 
        group: 

    - name: Fill AMI Metadata Text File With AMI Metadata
      blockinfile:
        path: /tmp/metadata.txt
        block: |
          "{{ ami_metadata }}"

    - name: Get Instance ID
      ec2_instance_info:
        aws_access_key: "{{ aws.access_key }}"
        aws_secret_key: "{{ aws.secret_key }}"
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "SOE_RHEL8SOE" 
          instance-state-name: [ "running"]
      register: ec2_info

    - name: Validate Instance ID
      debug: 
        var: ec2_info.instances[0].instance_id

